POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pbGJlIiwiaWQiOiI2NGFkNTNlNGUzOWU1ZDlmYmRlOTkyNzYiLCJpYXQiOjE2ODkwODA4NTV9.fE126uG5jryK0gR7l5ZQMEYDdWtxTT5TFl6mWygBcU8

{
  "title": "hyvä blogi",
  "author": "hyvä author",
  "url": "sembe.com",
  "likes": 19
}
